In [ ]:
 
import pandas as pd

# Path of the file to read
iowa_file_path = '../input/home-data-for-ml-course/train.csv'

home_data = pd.read_csv(iowa_file_path)

# Set up code checking
from learntools.core import binder
binder.bind(globals())
from learntools.machine_learning.ex3 import *

print("Setup Complete")

In [4]:
# print the list of columns in the dataset to find the name of the prediction target
home_data.describe()

                Id   MSSubClass      ...             YrSold      SalePrice
count  1460.000000  1460.000000      ...        1460.000000    1460.000000
mean    730.500000    56.897260      ...        2007.815753  180921.195890
std     421.610009    42.300571      ...           1.328095   79442.502883
min       1.000000    20.000000      ...        2006.000000   34900.000000
25%     365.750000    20.000000      ...        2007.000000  129975.000000
50%     730.500000    50.000000      ...        2008.000000  163000.000000
75%    1095.250000    70.000000      ...        2009.000000  214000.000000
max    1460.000000   190.000000      ...        2010.000000  755000.000000

[8 rows x 38 columns]

In [5]:
y = home_data.SalePrice

step_1.check()

Correct

In [7]:
# Create the list of features below
feature_names = ['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']

# select data corresponding to features in feature_names
X = home_data[feature_names]

step_2.check()

Correct

In [9]:
# Review data
# print description or statistics from X
X.head()

# print the top few lines
X

      LotArea  YearBuilt      ...       BedroomAbvGr  TotRmsAbvGrd
0        8450       2003      ...                  3             8
1        9600       1976      ...                  3             6
2       11250       2001      ...                  3             6
3        9550       1915      ...                  3             7
4       14260       2000      ...                  4             9
5       14115       1993      ...                  1             5
6       10084       2004      ...                  3             7
7       10382       1973      ...                  3             7
8        6120       1931      ...                  2             8
9        7420       1939      ...                  2             5
10      11200       1965      ...                  3             5
11      11924       2005      ...                  4            11
12      12968       1962      ...                  2             4
13      10652       2006      ...                  3             7
14      10920       1960      ...                  2             5
15       6120       1929      ...                  2             5
16      11241       1970      ...                  2             5
17      10791       1967      ...                  2             6
18      13695       2004      ...                  3             6
19       7560       1958      ...                  3             6
20      14215       2005      ...                  4             9
21       7449       1930      ...                  3             6
22       9742       2002      ...                  3             7
23       4224       1976      ...                  3             6
24       8246       1968      ...                  3             6
25      14230       2007      ...                  3             7
26       7200       1951      ...                  3             5
27      11478       2007      ...                  3             7
28      16321       1957      ...                  2             6
29       6324       1927      ...                  1             4
...       ...        ...      ...                ...           ...
1430    21930       2005      ...                  4             7
1431     4928       1976      ...                  2             5
1432    10800       1927      ...                  4             5
1433    10261       2000      ...                  3             8
1434    17400       1977      ...                  3             5
1435     8400       1962      ...                  3             7
1436     9000       1971      ...                  3             5
1437    12444       2008      ...                  2             7
1438     7407       1957      ...                  2             6
1439    11584       1979      ...                  3             6
1440    11526       1922      ...                  3            11
1441     4426       2004      ...                  1             3
1442    11003       2008      ...                  3            10
1443     8854       1916      ...                  2             4
1444     8500       2004      ...                  3             7
1445     8400       1966      ...                  3             6
1446    26142       1962      ...                  3             6
1447    10000       1995      ...                  3             8
1448    11767       1910      ...                  2             6
1449     1533       1970      ...                  1             3
1450     9000       1974      ...                  4             8
1451     9262       2008      ...                  3             7
1452     3675       2005      ...                  2             5
1453    17217       2006      ...                  3             6
1454     7500       2004      ...                  2             6
1455     7917       1999      ...                  3             7
1456    13175       1978      ...                  3             7
1457     9042       1941      ...                  4             9
1458     9717       1950      ...                  2             5
1459     9937       1965      ...                  3             6

[1460 rows x 7 columns]

In [10]:
from sklearn.tree import DecisionTreeRegressor
#specify the model. 
#For model reproducibility, set a numeric value for random_state when specifying the model
iowa_model = DecisionTreeRegressor(random_state=1)

# Fit the model
iowa_model.fit(X,y)

step_3.check()

Correct

In [11]:
predictions = iowa_model.predict(X.head())
print(predictions)
step_4.check()
y.head()

[208500. 181500. 223500. 140000. 250000.]

Incorrect: Your predictions are shape (5,). Expected shape (1460,)

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64